REGISTRATION:
-------------
CREATE TABLE ADMINS
(
 ADMIN_ID BIGINT(10) NOT NULL,
 EMAIL_ID VARCHAR(50) NOT NULL,
 PWD VARCHAR(50) NOT NULL,
 STATUS INT(1) NOT NULL,
 IS_FTL INT(1) NOT NULL,
 CREATED_BY        BIGINT(10) NULL,
 CREATED_DATE      BIGINT NULL,
 MODIFIED_BY       BIGINT(10) NULL,
 MODIFIED_DATE     BIGINT NULL,
 VERSION           INT(1) NULL,
 DELETED           INT(1) NULL,
 CONSTRAINT ADMINS_PK PRIMARY KEY (ADMIN_ID),
 CONSTRAINT ADMINS_EMAILID_UNIQUE UNIQUE (EMAIL_ID)
);


CREATE TABLE ADMIN_DETAILS
(
 ADMIN_NAME VARCHAR(25) NOT NULL,
 ADMIN_MOBILE VARCHAR(10) NOT NULL,
 OFFICE_LANDLINE VARCHAR(15) NULL,
 ADMIN_ADDRESS VARCHAR(100) NULL,
 ADMIN_ST_OR_UT INT(4) NOT NULL,
 GSTIN_NO VARCHAR(20) NOT NULL,
 EFFECTIVE_DATE BIGINT NULL,
 CREATED_BY        BIGINT(10) NOT NULL,
 CREATED_DATE      BIGINT NULL,
 MODIFIED_BY       BIGINT(10) NULL,
 MODIFIED_DATE     BIGINT NULL,
 VERSION           INT(1) NULL,
 DELETED           INT(1) NULL,
 CONSTRAINT ADMIN_DETAILS_PK PRIMARY KEY (CREATED_BY),
 CONSTRAINT ADMIN_DETAILS_STORUT_FK FOREIGN KEY (ADMIN_ST_OR_UT) REFERENCES STATES_AND_UT_ENUM(ID)
);

CREATE TABLE ACCOUNT_ACTIVATION (
    ADMIN_ID BIGINT(10) NOT NULL,
    REQUEST_TYPE INT(1) NOT NULL,
    ACTIVATION_CODE  VARCHAR(50) NOT NULL,
    CREATED_DATE BIGINT NULL,

    CONSTRAINT ACCOUNT_ACTIVATION_PK PRIMARY KEY (ADMIN_ID,REQUEST_TYPE)
);







CREATE TABLE USER_DETAILS (
    USER_ID BIGINT(10) NOT NULL,
    PWD VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(25) NOT NULL,
    USER_MOBILE VARCHAR(10) NOT NULL,
    USER_ADDRESS VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(50) NULL,
    STATUS INT(1) NOT NULL,
    CREATED_BY        BIGINT(10) NULL,
    CREATED_DATE      BIGINT NULL,
    MODIFIED_BY       BIGINT(10) NULL,
    MODIFIED_DATE     BIGINT NULL,
    VERSION           INT(1) NULL,
    DELETED           INT(1) NULL,
    CONSTRAINT USER_DETAILS_PK PRIMARY KEY (USER_ID)
);
ALTER TABLE USER_DETAILS MODIFY COLUMN USER_ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE USER_DETAILS AUTO_INCREMENT=1000001;
