CREATE TABLE STATES_AND_UT_ENUM (
    ID INT(2) NOT NULL,
    STATE_OR_UT_CODE VARCHAR(2) NOT NULL,
    STATE_OR_UT_NAME VARCHAR(50) NOT NULL,
 CONSTRAINT STATES_AND_UT_ENUM_PK PRIMARY KEY (ID)
);
ALTER TABLE STATES_AND_UT_ENUM MODIFY COLUMN ID INT(2) AUTO_INCREMENT;
ALTER TABLE STATES_AND_UT_ENUM AUTO_INCREMENT=1;


INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('01','JAMMU & KASHMIR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('02','HIMACHAL PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('03','PUNJAB');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('04','CHANDIGARH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('05','UTTARAKHAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('06','HARYANA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('07','DELHI');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('08','RAJASTHAN');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('09','UTTAR PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('10','BIHAR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('11','SIKKIM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('12','ARUNACHAL PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('13','NAGALAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('14','MANIPUR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('15','MIZORAM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('16','TRIPURA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('17','MEGHALAYA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('18','ASSAM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('19','WEST BENGAL');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('20','JHARKHAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('21','ODISHA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('22','CHHATTISGARH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('23','MADHYA PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('24','GUJARAT');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('25','DAMAN & DIU');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('26','DADRA & NAGAR HAVELI');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('27','MAHARASHTRA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('29','KARNATAKA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('30','GOA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('31','LAKSHDWEEP');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('32','KERALA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('33','TAMIL NADU');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('34','PONDICHERRY');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('35','ANDAMAN & NICOBAR ISLANDS');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('36','TELANGANA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('37','ANDHRA PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('97','OTHER TERRITORY');

------------------------------