REGISTRATION:
-------------
CREATE TABLE ADMINS
(
 ADMIN_ID BIGINT(10) NOT NULL,
 EMAIL_ID VARCHAR(50) NOT NULL,
 PWD VARCHAR(50) NOT NULL,
 STATUS INT(1) NOT NULL,
 IS_FTL INT(1) NOT NULL,
 CREATED_BY        BIGINT(10) NULL,
 CREATED_DATE      BIGINT NULL,
 MODIFIED_BY       BIGINT(10) NULL,
 MODIFIED_DATE     BIGINT NULL,
 VERSION           INT(1) NULL,
 DELETED           INT(1) NULL,
 CONSTRAINT ADMINS_PK PRIMARY KEY (ADMIN_ID),
 CONSTRAINT ADMINS_EMAILID_UNIQUE UNIQUE (EMAIL_ID)
);


CREATE TABLE ADMIN_DETAILS
(
 ADMIN_NAME VARCHAR(25) NOT NULL,
 ADMIN_MOBILE VARCHAR(10) NOT NULL,
 OFFICE_LANDLINE VARCHAR(15) NULL,
 ADMIN_ADDRESS VARCHAR(100) NULL,
 ADMIN_ST_OR_UT INT(4) NOT NULL,
 GSTIN_NO VARCHAR(20) NOT NULL,
 EFFECTIVE_DATE BIGINT NULL,
 CREATED_BY        BIGINT(10) NOT NULL,
 CREATED_DATE      BIGINT NULL,
 MODIFIED_BY       BIGINT(10) NULL,
 MODIFIED_DATE     BIGINT NULL,
 VERSION           INT(1) NULL,
 DELETED           INT(1) NULL,
 CONSTRAINT ADMIN_DETAILS_PK PRIMARY KEY (CREATED_BY),
 CONSTRAINT ADMIN_DETAILS_STORUT_FK FOREIGN KEY (ADMIN_ST_OR_UT) REFERENCES STATES_AND_UT_ENUM(ID)
);

CREATE TABLE ACCOUNT_ACTIVATION (
    ADMIN_ID BIGINT(10) NOT NULL,
    REQUEST_TYPE INT(1) NOT NULL,
    ACTIVATION_CODE  VARCHAR(50) NOT NULL,
    CREATED_DATE BIGINT NULL,

    CONSTRAINT ACCOUNT_ACTIVATION_PK PRIMARY KEY (ADMIN_ID,REQUEST_TYPE)
);




CREATE TABLE STATES_AND_UT_ENUM (
    ID INT(2) NOT NULL,
    STATE_OR_UT_CODE VARCHAR(2) NOT NULL,
    STATE_OR_UT_NAME VARCHAR(50) NOT NULL,
 CONSTRAINT STATES_AND_UT_ENUM_PK PRIMARY KEY (ID)
);
ALTER TABLE STATES_AND_UT_ENUM MODIFY COLUMN ID INT(2) AUTO_INCREMENT;
ALTER TABLE STATES_AND_UT_ENUM AUTO_INCREMENT=1;


INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('01','JAMMU & KASHMIR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('02','HIMACHAL PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('03','PUNJAB');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('04','CHANDIGARH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('05','UTTARAKHAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('06','HARYANA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('07','DELHI');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('08','RAJASTHAN');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('09','UTTAR PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('10','BIHAR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('11','SIKKIM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('12','ARUNACHAL PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('13','NAGALAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('14','MANIPUR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('15','MIZORAM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('16','TRIPURA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('17','MEGHALAYA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('18','ASSAM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('19','WEST BENGAL');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('20','JHARKHAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('21','ODISHA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('22','CHHATTISGARH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('23','MADHYA PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('24','GUJARAT');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('25','DAMAN & DIU');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('26','DADRA & NAGAR HAVELI');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('27','MAHARASHTRA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('29','KARNATAKA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('30','GOA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('31','LAKSHDWEEP');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('32','KERALA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('33','TAMIL NADU');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('34','PONDICHERRY');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('35','ANDAMAN & NICOBAR ISLANDS');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('36','TELANGANA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('37','ANDHRA PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('97','OTHER TERRITORY');

------------------------------


CREATE TABLE USER_DETAILS (
    USER_ID BIGINT(10) NOT NULL,
    PWD VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(25) NOT NULL,
    USER_MOBILE VARCHAR(10) NOT NULL
    USER_ADDRESS VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(50) NULL,
    STATUS INT(1) NOT NULL,
    CREATED_BY        BIGINT(10) NULL,
    CREATED_DATE      BIGINT NULL,
    MODIFIED_BY       BIGINT(10) NULL,
    MODIFIED_DATE     BIGINT NULL,
    VERSION           INT(1) NULL,
    DELETED           INT(1) NULL,
    CONSTRAINT USER_DETAILS_PK PRIMARY KEY (ID)
);
ALTER TABLE USER_DETAILS MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE USER_DETAILS AUTO_INCREMENT=1000001;
