REGISTRATION:
-------------
CREATE TABLE ADMINS
(
 ADMIN_ID BIGINT(10) NOT NULL,
 EMAIL_ID VARCHAR(50) NOT NULL,
 PWD VARCHAR(50) NOT NULL,
 STATUS INT(1) NOT NULL,
 IS_FTL INT(1) NOT NULL,
 CREATED_BY        BIGINT(10) NULL,
 CREATED_DATE      BIGINT NULL,
 MODIFIED_BY       BIGINT(10) NULL,
 MODIFIED_DATE     BIGINT NULL,
 VERSION           INT(1) NULL,
 DELETED           INT(1) NULL,
 CONSTRAINT ADMINS_PK PRIMARY KEY (ADMIN_ID),
 CONSTRAINT ADMINS_EMAILID_UNIQUE UNIQUE (EMAIL_ID)
);


CREATE TABLE ADMIN_DETAILS
(
 ADMIN_NAME VARCHAR(25) NOT NULL,
 ADMIN_MOBILE VARCHAR(10) NOT NULL,
 OFFICE_LANDLINE VARCHAR(15) NULL,
 ADMIN_ADDRESS VARCHAR(100) NULL,
 ADMIN_ST_OR_UT INT(4) NOT NULL,
 GSTIN_NO VARCHAR(20) NOT NULL,
 EFFECTIVE_DATE BIGINT NULL,
 CREATED_BY        BIGINT(10) NOT NULL,
 CREATED_DATE      BIGINT NULL,
 MODIFIED_BY       BIGINT(10) NULL,
 MODIFIED_DATE     BIGINT NULL,
 VERSION           INT(1) NULL,
 DELETED           INT(1) NULL,
 CONSTRAINT ADMIN_DETAILS_PK PRIMARY KEY (CREATED_BY),
 CONSTRAINT ADMIN_DETAILS_STORUT_FK FOREIGN KEY (ADMIN_ST_OR_UT) REFERENCES STATES_AND_UT_ENUM(ID)
);

CREATE TABLE ACCOUNT_ACTIVATION (
    ADMIN_ID BIGINT(10) NOT NULL,
    REQUEST_TYPE INT(1) NOT NULL,
    ACTIVATION_CODE  VARCHAR(50) NOT NULL,
    CREATED_DATE BIGINT NULL,

    CONSTRAINT ACCOUNT_ACTIVATION_PK PRIMARY KEY (ADMIN_ID,REQUEST_TYPE)
);







CREATE TABLE USER_DETAILS (
    USER_ID BIGINT(10) NOT NULL,
    PWD VARCHAR(50) NOT NULL,
    USER_NAME VARCHAR(25) NOT NULL,
    USER_MOBILE VARCHAR(10) NOT NULL,
    USER_ADDRESS VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(50) NULL,
    STATUS INT(1) NOT NULL,
    CREATED_BY        BIGINT(10) NULL,
    CREATED_DATE      BIGINT NULL,
    MODIFIED_BY       BIGINT(10) NULL,
    MODIFIED_DATE     BIGINT NULL,
    VERSION           INT(1) NULL,
    DELETED           INT(1) NULL,
    CONSTRAINT USER_DETAILS_PK PRIMARY KEY (USER_ID)
);
ALTER TABLE USER_DETAILS MODIFY COLUMN USER_ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE USER_DETAILS AUTO_INCREMENT=1000001;

alter table user_details change id USER_ID BIGINT(10) NOT NULL;
SELECT * FROM USER_DETAILS WHERE CREATED_BY=1212121212 AND DELETED=0;

select * from user_details;

update user_details set status =1 where user_id=111111;



-------------

CREATE TABLE CVO_DATA (
	ID BIGINT(10) NOT NULL,
	CVO_NAME VARCHAR(50) NOT NULL,
	CVO_ADDRESS VARCHAR(100) NOT NULL,
	CVO_CONTACT VARCHAR(15) NOT NULL,
	CVO_CAT INT(1) NOT NULL,
	IS_GST_REG INT(1) NOT NULL,
	CVO_TIN VARCHAR(20) NULL,
	CVO_EMAIL VARCHAR(50) NULL,
	CVO_PAN VARCHAR(15) NULL,
	OBAL VARCHAR(13) NOT NULL,
	CBAL VARCHAR(13) NOT NULL,
	EBAL VARCHAR(13) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT CVO_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE CVO_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE CVO_DATA AUTO_INCREMENT=1000001;

SELECT * FROM CVO_DATA;

CREATE TABLE CVO_BALANCE_DATA (
 ID 		  BIGINT(10) NOT NULL AUTO_INCREMENT,
 REF_ID 	  BIGINT(10) NOT NULL,
 CVOFLAG 	  INT(1) NOT NULL,
 INV_REF_NO   VARCHAR(30) NOT NULL,
 INV_DATE 	  BIGINT(20) NOT NULL,
 TRANS_TYPE   INT(1) NOT NULL,
 CVO_CAT 	  INT(1) NOT NULL,
 CVO_REFID 	  BIGINT(10) NOT NULL,
 AMOUNT 	  VARCHAR(13) NOT NULL,
 CBAL_AMOUNT  VARCHAR(20) NOT NULL,
 DISCOUNT 	  VARCHAR(10) NULL,
 CREATED_BY      		BIGINT(10) NULL,
 CREATED_DATE  			BIGINT NULL,
 MODIFIED_BY          	BIGINT(10) NULL,
 MODIFIED_DATE         	BIGINT NULL,
 VERSION               	INT(1) NULL,
 DELETED               	INT(1) NULL,

 CONSTRAINT CVO_BALANCE_DATA_PK PRIMARY KEY (ID)
);


SELECT * FROM CVO_BALANCE_DATA;

CREATE TABLE BANK_DATA (
	ID BIGINT(10) NOT NULL,
	BANK_CODE VARCHAR(20) NULL,
	BANK_NAME VARCHAR(25) NOT NULL,
	BANK_ACC_NO VARCHAR(20) NOT NULL,
	BANK_BRANCH VARCHAR(50) NULL,
	BANK_IFSC_CODE VARCHAR(15) NULL,
	ACC_OB DECIMAL(13,2) NOT NULL,
	ACC_CB DECIMAL(13,2) NOT NULL,
	BANK_ADDR VARCHAR(250) NULL,
	OD_AND_LOAN_ACCEPTABLE_BAL VARCHAR(13) NOT NULL DEFAULT "NA",
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT BANK_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE BANK_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE BANK_DATA AUTO_INCREMENT=1000001;

SELECT * FROM BANK_DATA;

CREATE TABLE FLEET_DATA (
	ID BIGINT(10) NOT NULL,
	VEHICLE_NO VARCHAR(10) NOT NULL,
	VEHICLE_MAKE VARCHAR(25) NOT NULL,
	VEHICLE_TYPE INT(1) NOT NULL,
	VEHICLE_USUAGE INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT FLEET_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE FLEET_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE FLEET_DATA AUTO_INCREMENT=1000001;

SELECT * FROM FLEET_DATA ;

UPDATE FLEET_DATA SET CREATED_BY=1212121212 WHERE ID=1000001;
SELECT * FROM STAFF_DATA;